name: Run and Cache Benchmarks

on:
pull_request:
    types: [opened, reopened, edited, synchronize]

jobs:
run_benchmarks:
    name: Run PR Benchmarks
    runs-on: ubuntu-latest
    steps:
    - name: checkout
        uses: actions/checkout@v4

    - name: Upload PR benchmark Results
        uses: actions/upload-artifact@v4
        with:
        name: pr.txt
        path: pr.txt

    - name: Upload base benchmark Results
        uses: actions/upload-artifact@v4
        with:
        name: base.txt
        path: base.txt

    - name: Upload GitHub Event
        uses: actions/upload-artifact@v4
        with:
        name: event.json
        path: event.json
